#-------------------------------
# Site Settings
title: 米淉 MiGuo
description: 喜歡畫可愛的女孩子～如果有任何委託的需求，歡迎來信詢問～
logo: '/assets/images/home/logo_dark.png' # You can add own logo. For example '/images/logo.png'.
logo_dark: '/assets/images/home/logo_light.png'
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# 導航設定 Navigation Settings
menu_settings:
  menu_items:
    - title: '首頁'
      url: '/'

    - title: '插畫作品'
      url: '/projects/'
      
    - title: '發起委託'
    - url: '/services/'
      
    
      submenu:
      #- url: '/clients/'
      #  title: '案例'

      #- url: '/about/'
      #  title: '關於我'

      #- url: '/videos/'
      #  title: '影片'

      #- url: '/archive/'
      #  title: '檔案館'

      #- url: '/elements/'
      #  title: '元素'

      - url: '/latest/'
        title: '最新'
        
      - url: '/faq/'
        title: '常見問題'

# 號召行動按鈕 Call to action button
cta_button:
  enable: true
  cta_button_link: "https://miguo.fanbox.cc/"
  cta_button_text: PIXIV FANBOX


# 首頁封面圖片 Home Cover Image
home_cover_image: /assets/images/home/bg.png


#-------------------------------
# 作者設定 Author Settings
author:
  author_name: 米淉 MiGuo
  author_avatar: /assets/images/home/256px_24fps.gif


#-------------------------------
# 英雄設定 Hero Settings
hero:
  enable: true
  hero_avatar: /assets/images/home/256px_24fps.gif
  hero_title: 米淉 MiGuo
  hero_description: <p>喜歡畫可愛的女孩子～<br>如果有任何委託的需求，歡迎來信詢問～<br><br>かわいい女の子を描くのが好きにゃ～！<br>もしご依頼があれば、ぜひご連絡ください～<br><br>Email | <a href="mailto:hi@miguo.art">hi@miguo.art</a></p>


#-------------------------------
# 社群連結 Social Settings
social:
- {icon: "fa-brands fa-pixiv", name: "pixiv", link: "https://www.pixiv.net/users/25343499"}
- {icon: "fa-brands fa-x-twitter", name: "X (twitter)", link: "https://x.com/miguo_tw"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/miguo-art.bsky.social"}
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://www.facebook.com/miguotw"}
- {icon: "fa-brands fa-twitch", name: "Twitch", link: "https://www.twitch.tv/miguotw"}
- {icon: "fa-brands fa-youtube", name: "YouTube", link: "https://www.youtube.com/@miguo_tw"}
- {icon: "fa-brands fa-discord", name: "Discord", link: "https://discord.com/invite/krSbg8ZrVx"}

# Example of adding a new link to the hero and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# 項目部分設定 Projects Section Settings
projects:
  enable: true
  projects_title: 插畫作品 Illustration Works


#-------------------------------
# 部落格設定 Section Blog Settings
blog:
  enable: true
  blog_title: Writings


#-------------------------------
# 簡訊設定 Newsletter Settings
mailchimp:
  enable: false
  mailchimp_image: '/images/20.jpg'
  mailchimp_title: Stay Inspired Weekly
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  button_text: Send Message

# NOTE
# Tarne theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: miguo # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: 你有什麼想法？
  disqus_button_text: 顯示評論區


#-------------------------------
# Google Analytics
google_analytics: G-TPQJL9B9T1 # Add your GA Tracking Id