#-------------------------------
# ç¶²ç«™è¨­å®š Site Settings
title: ç±³æ·‰ MiGuo
logo: "/assets/images/main/logo_light.png" # You can add own logo. For example '/assets/images/logo.png'.
logo_dark: "/assets/images/main/logo_dark.png"
description: å–œæ­¡ç•«å¯æ„›çš„å¥³å­©å­ï½å¦‚æœæœ‰ä»»ä½•å§”è¨—çš„éœ€æ±‚ï¼Œæ­¡è¿ä¾†ä¿¡è©¢å•ï½
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# å°èˆªè¨­å®š Navigation Settings
menu_settings:
  menu_items:
    - title: 'é¦–é '
      url: '/'

    - title: 'åŸå‰µæ’ç•«'
      url: '/tags/?tag=åŸå‰µæ’ç•«'
    
    - title: 'æ’ç•«ä½œå“'
      url: '/blog/'

    - title: 'å…¶ä»–å°ˆæ¡ˆ'
      url: '/projects/'
    
    - title: 'è²¼åœ– | ç±³æ·‰å­æ—¥å¸¸'
      url: '/project/lineè²¼åœ–-ç±³æ·‰å­æ—¥å¸¸'

    - title: 'Live2D | çŒ«åˆã¿ã¤ã‚‹'
      url: '/project/live2d-çŒ«åˆã¿ã¤ã‚‹'


# è™Ÿå¬è¡Œå‹•æŒ‰éˆ• Call to action button
cta_button:
  enable: true
  cta_button_link: "https://miguo.fanbox.cc/"
  cta_button_text: pixiv FANBOX


#-------------------------------
# ä½œè€…è¨­å®š Author Settings
author:
  author_intro: ç±³æ·‰ MiGuo
  author_name: ç±³æ·‰ MiGuo
  author_role: # Illustrator
  author_avatar: /assets/images/main/avatar_150px.gif


#-------------------------------
# å´é‚Šæ¬„éƒ¨åˆ†è¨­ç½® Sidebar Section Settings
sidebar:
  sidebar_title: ãƒ¾(*Î¦Ï‰Î¦)ãƒ„ # You can add an 'em' element to highlight text.
  sidebar_description: <p>å–œæ­¡ç•«å¯æ„›çš„å¥³å­©å­ï½<br>å¦‚æœæœ‰ä»»ä½•å§”è¨—çš„éœ€æ±‚ï¼Œæ­¡è¿ä¾†ä¿¡è©¢å•ï½<br><br>ã‹ã‚ã„ã„å¥³ã®å­ã‚’æãã®ãŒå¥½ãã«ã‚ƒï½ï¼<br>ã‚‚ã—ã”ä¾é ¼ãŒã‚ã‚Œã°ã€ãœã²ã”é€£çµ¡ãã ã•ã„ï½<br><br>Emailï¼š<a href="mailto:creative@miguo.art">creative@miguo.art</a></p>


# ç¤¾ç¾¤é€£çµ Social Links
social:
- {icon: "fa-brands fa-pixiv", name: "pixiv", link: "https://www.pixiv.net/users/25343499"}
- {icon: "fa-brands fa-x-twitter", name: "X", link: "https://x.com/miguo_tw"}
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://www.facebook.com/miguotw"}
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/miguo-art.bsky.social"}
- {icon: "fa-brands fa-twitch", name: "Twitch", link: "https://www.twitch.tv/miguotw"}
- {icon: "fa-brands fa-youtube", name: "YouTube", link: "https://www.youtube.com/@miguo_tw"}
- {icon: "fa-brands fa-discord", name: "Discord", link: "https://discord.com/invite/krSbg8ZrVx"}
#- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/miguotw"}
#- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
#- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
#- {icon: "fa-brands fa-spotify", name: "Spotify", link: "https://spotify.com"}
#- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# ç•«å»Šè¨­ç½® Gallery Settings
gallery:
  enable: true
  gallery_title: ç²¾é¸ä½œå“ã€€<em>Selected Works</em> # You can add an 'em' element to highlight text.
  gallery_description: æœ€æ»¿æ„çš„ä½œå“ï¼Œä¸å®šæœŸæ›´æ–°ï¼
  gallery_caption:

gallery_images:
  - alt: 'æ—§æ­£æœˆãŠã‚ã§ã¨ã†ï¼ğŸª­âœ¨'
    url: '/assets/images/gallery/126522361_p0.jpg'

  - alt: 'å°æ‚ªé­”å¸¸é—‡ãƒˆãƒ¯ğŸ‘¿âœ¨ğŸ’–'
    url: '/assets/images/gallery/126083127_p0.jpg'

  - alt: 'ä¸‹æ±Ÿã‚³ãƒãƒ«'
    url: '/assets/images/gallery/111714463_p0.jpg'

  #- alt: 'ãƒãƒ¬ãƒ³ã‚¿ã‚¤ãƒ³ãƒŸãƒ‹ã‚²ãƒ¼ãƒ ï¼ğŸ’–ğŸ–Œï¸'
  #  url: '/assets/images/gallery/A0201@B5.jpg'

  #- alt: 'ã‚ãªãŸã®ãƒ—ãƒ¬ã‚¼ãƒ³ãƒˆï¼ğŸ€âœ¨'
  #  url: '/assets/images/gallery/127752279_p0.jpg'


#-------------------------------
# æ’ç•«ä½œå“ Blog Section Settings
blog:
  enable: true
  blog_title: æ’ç•«ä½œå“ã€€<em>Illustration Works</em> # You can add an 'em' element to highlight text.
  blog_description: é€™è£¡æ”¶éŒ„ä¸€äº›æˆ‘çš„æ’ç•«ä½œå“ï¼Œ<br>é€™äº›ä½œå“é€šå¸¸ä¹Ÿå¯ä»¥åœ¨ <a href="https://www.pixiv.net/users/25343499">pixiv (ãƒ”ã‚¯ã‚·ãƒ–)</a> ä¸ŠæŸ¥çœ‹ã€‚


#-------------------------------
# å…¶ä»–å°ˆæ¡ˆ Projects Settings
projects:
  enable: true
  projects_title: å…¶ä»–å°ˆæ¡ˆã€€<em>Other Projects</em> # You can add an 'em' element to highlight text.
  projects_description: å…¶ä»–ä¸€äº›æ±æ±ã€‚å¥½å§ï¼Œæˆ‘æƒ³ä¸åˆ°äº†ã€‚


#-------------------------------
# Testimonials Settings
testimonials:
  enable: false
  testimonials_title: Trusted by <em>Professionals</em> # You can add an 'em' element to highlight text.
  testimonials_description: Join our community of creative professionals where you can develop your talents and reach new heights in design.

testimonial-items:
  - name: Amelia Jones
    image: "/assets/images/client-1.jpg"
    designation : Network Engineer
    content : This product designer is an expert in his field. His ability to understand the needs of clients and create designs that satisfy them is astounding.

  - name: Ethan Robinson
    image: "/assets/images/client-2.jpg"
    designation : Blockchain Developer
    content : Kevin is a true visionary in the field of product design. His ability to think outside the box and push boundaries is what sets him apart from the rest.

  - name: Matthew Garcia
    image: "/assets/images/client-3.jpg"
    designation : IT Support Specialist
    content : I cannot recommend this designer highly enough. Their designs are not only visually stunning but also highly functional, making them perfect for our needs.


#-------------------------------
# å¸¸è¦‹å•é¡Œè¨­å®š Faq (Frequently asked questions) Settings
faq:
  enable: false
  faq_title: Questions? <em>Answers</em>. # You can add an 'em' element to highlight text.
  faq_description: Find solutions to common queries here.

faq_items:
  - title: What are your main areas of expertise in product design?
    description: My specialization includes user interface (UI) and user experience (UX) design, prototyping, as well as researching and testing user needs.

  - title: Can you provide examples of your work?
    description: Yes, on my website, you can find a portfolio with examples of my projects and designs.

  - title: What is your experience with various platforms and devices?
    description: I have extensive experience working with various platforms, including websites, mobile applications, tablets, and other devices.

  - title: What tools and software do you use for work?
    description: I work with tools such as Sketch, Adobe XD, Figma, InVision for creating designs and prototypes, and also use Jira and Trello for project management.

  - title: How long does it take to develop a product design?
    description: The development time depends on the complexity of the project. Usually, creating a product design takes from several weeks to several months.

  - title: How can I contact you to discuss my project?
    description: You can contact me through the contact form on my website or directly via email. I'm always open to new projects and ready to discuss your idea.


#-------------------------------
# ç°¡è¨Šè¨­å®š Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Subscribe to Our <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Join now and never miss out on our stuff again. Because you are worth it!
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# è¯çµ¡æ–¹å¼ Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Baleon comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: miguo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-TPQJL9B9T1 # Add your GA Tracking Id